Style/FrozenStringLiteralComment:
    Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Style/Next:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Style/StringLiterals:
  Enabled: false
